set(_CATKIN_CURRENT_PACKAGE "multi_master_bridge")
set(multi_master_bridge_VERSION "0.0.0")
set(multi_master_bridge_MAINTAINER "mrsang <mrsang@todo.todo>")
set(multi_master_bridge_PACKAGE_FORMAT "1")
set(multi_master_bridge_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(multi_master_bridge_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(multi_master_bridge_BUILDTOOL_DEPENDS "catkin")
set(multi_master_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(multi_master_bridge_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(multi_master_bridge_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(multi_master_bridge_TEST_DEPENDS )
set(multi_master_bridge_DOC_DEPENDS )
set(multi_master_bridge_DEPRECATED "")